### ISSUE TITLE
Checkbox group missing has-value attribute and Lumo required indicator

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-checkbox#122]
The `has-value` attribute needs to be implemented. Also, following styles to be added for Lumo:

```css
      :host([required]) [part="label"] {
        padding-right: 1em;
      }
      [part="label"]::after {
        content: var(--lumo-required-field-indicator, "•");
        transition: opacity 0.2s;
        opacity: 0;
        color: var(--lumo-primary-text-color);
        position: absolute;
        right: 0;
        width: 1em;
        text-align: center;
      }
      :host([required]:not([has-value])) [part="label"]::after {
        opacity: 1;
      }
````
Material theme also needs required indicator.
